name: 1 - hellow - world

on: workflow_dispatch

jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - name: Print hellow
          run: echo "hellow world"
    
    second-job:
      runs-on: ubuntu-latest
      steps:
        - name: Print Hi To You
          run: echo "Hi To You" 

        - name: I Will Suc.
          run: exit 0

        - name: Say Goodbye
          run: echo "Goodbye"

          
