name: 1 - hellow - world

on: push

jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - name: Print hellow
          run: echo "hellow world"
        
        - name: Print Goodbye
          run: rcho "Goodbye"